### ISSUE TITLE
Session is destroyed after page is refreshed

### ISSUE THREAD

**Issue by ayushman1024** [ayushman1024/TASK-Management-System#7]
User session is destroyed after page is refreshed. Use session storage to store, user credentials during session.
**sessionStorage.setItem('data', JSON.stringify(this.data));**

**Comment by ayushman1024** [comment]
This has been fixed in below commit
commit   4ab67fa422fa03415e0cb0e70481aca321c4f51a

**Comment by AbhishekAnand01** [comment]
Just a suggestion 

we must not store any auth data/user info like token, userName  etc in plane text in sessionstorage/localstorage.

So request you to please encrypt data before storing in sessionstorage/localstorage.

Thank you
